{{- if and .Values.monitoring.enabled .Values.monitoring.serviceMonitor.enabled }}
{{- if .Values.monitoring.vppExporter.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "travelping-upf-loadtest.fullname" . }}-upf
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "travelping-upf-loadtest.labels" . | nindent 4 }}
    {{- with .Values.monitoring.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "travelping-upf-loadtest.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: upf
      service: metrics
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout }}
      metricRelabelings:
        {{- range $name, $iface := .Values.upf.interfaces }}
        - sourceLabels: [interface]
          regex: {{ $iface.metricIndex | quote }}
          targetLabel: interface_name
          replacement: {{ $name | quote }}
        {{- end }}
{{- end }}
{{- if and .Values.monitoring.vppExporter.enabled .Values.monitoring.trexExporter.enabled }}
---
{{- end }}
{{- if .Values.monitoring.trexExporter.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "travelping-upf-loadtest.fullname" . }}-trex
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "travelping-upf-loadtest.labels" . | nindent 4 }}
    {{- with .Values.monitoring.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "travelping-upf-loadtest.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: trex
      service: metrics
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout }}
{{- end }}
{{- end }}
